### ISSUE TITLE
ClerkClient typo in `unLockUser` - duplicate `lockUser` method

### ISSUE THREAD

**Issue by dimkl** [ravikrsngh/clerk_django#1]
Instead of having `unLockUser` method in the `resources/user` the `lockUser` is defined 2 times even though the 2nd one is calling the unlock endpoint.

ref: https://github.com/ravikrsngh/clerk_django/blob/ad69dd267551fad53d458bef548fab99b73e6c2f/clerk_django/resources/user.py#L38

**Comment by ravikrsngh** [comment]
Thanks for pointing this out.
